services:
  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8080:8000"
    environment:
      - MONGODB_URL=mongodb://db:27017
      - MONGODB_DB_NAME=library_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  mongo_data:
